headers = {
    'Accept': '*/*',
    'Accept-Language': 'ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7',
    'Cache-Control': 'max-age=0',
    'Connection': 'keep-alive',
    'Content-Type': 'multipart/form-data; boundary=----WebKitFormBoundaryplq1xwc3TDFb1nuj',
    'Origin': 'https://www.dns-shop.ru',
    'Referer': 'https://www.dns-shop.ru/catalog/17a8a05316404e77/planshety/no-referrer',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'User-Agent': 'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36',
    'X-CSRF-Token': 'UFRML4Flb2h9SO_cMA3pZ2ML0BrKVrBCrbYjsJN76FoePwZ90CwFGBgtsJt3eZsmMmKyfYkQnXP9g2Hl2Q_FFg==',
    'X-Requested-With': 'XMLHttpRequest',
    'sec-ch-ua': '"Google Chrome";v="111", "Not(A:Brand";v="8", "Chromium";v="111"',
    'sec-ch-ua-mobile': '?0',
    'sec-ch-ua-platform': '"Linux"',
}
